# Generated by Django 4.0.4 on 2022-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
